version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.10
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: ionicons
    versions:
    - 5.5.0
  - dependency-name: "@angular/google-maps"
    versions:
    - 11.2.2
  - dependency-name: rimraf
    versions:
    - 3.0.2
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.2
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: handlebars
    versions:
    - 4.7.7
  - dependency-name: morgan
    versions:
    - 1.10.0
  - dependency-name: marked
    versions:
    - 0.3.19
  - dependency-name: dot
    versions:
    - 1.1.3
